import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderCurriculo from '../components/HeaderCurriculo'
import Objetivo from '../components/Objetivo'
import { useState } from 'react'

import BaixarC from '../components/BaixarC'






export default function Home({abrirCurriculo}) {
  const closeBanner=()=>{
        
    setHomeBanner(<BaixarC closeCurriculo={closeCurriculo}/>)
 }
 const closeCurriculo =() => {
    setHomeBanner(<></>)
 }
 
 const [homeBanner,setHomeBanner]=useState(<></>)
 
  return (
    <>
    {homeBanner}
    <div className={styles.container}>
      <Head>
        <title>Gleiton Aparecido Soares de Souza - Curriculum Vitae</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.corpoCurriculo}>
      
        < HeaderCurriculo abrirCurriculo={closeBanner}/>
        < Objetivo />
      </div>
    </div>
    </>
  )
}
