import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderCurriculo from '../components/HeaderCurriculo'
import Objetivo from '../components/Objetivo'

export const config = { amp: true }


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gleiton Aparecido Soares de Souza - Curriculum Vitae</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.corpoCurriculo}>
        < HeaderCurriculo />
        < Objetivo />
      </div>
    </div>
  )
}
